### ISSUE TITLE
Finalise first version of manual gating app

### ISSUE THREAD

**Issue by agouy** [tercen/manual_gating_shiny_operator#1]
- [x] Move transforms out of the operator + other small things
- [x] Populate README
- [x] Test operator on tercen.com (make sure C++ code compilation not an issue)

**Comment by tsmonteiro** [comment]
Just a quick update on the C++ point: I have noticed that Faris is running the operator on tercen.com, so I beleive it is safe to assume it is working properly

**Comment by tsmonteiro** [comment]
The tasks are all implemented in version 0.4.3 of the operator. 

Due to permission issues, it is necessary to inform in which transform the data is (operator parameter).

**Comment by agouy** [comment]
Under testing and validation

**Comment by agouy** [comment]
Feedback will be gathered in issue https://github.com/tercen/manual_gating_shiny_operator/issues/4
