### ISSUE TITLE
manual gating view (dotplot) can not be reopened 

### ISSUE THREAD

**Issue by MahoNagasawa** [tercen/manual_gating_shiny_operator#11]
Once the data step is completed its run and the step is closed to continue for the next data step, the bivariate plot won't be available again (the screen become gray) unless reset the step that also reset the gate and population name, so a researcher needs to start over again. Not ideal.

![image](https://user-images.githubusercontent.com/87133370/193529878-45bbcd82-1c25-4c4c-8e0e-97d058ae28a6.png)
![image](https://user-images.githubusercontent.com/87133370/193523957-95f73e38-a27e-4f51-9a3e-906ecf5d030f.png)

**Comment by agouy** [comment]
@MahoNagasawa After the first run, it is unfortunately not possible to reload the application as the computed results cannot be edited. However, the plot can still be found in the computed tables (table 3 I think) and not in the operator view tab.
Ultimately, this plot will be displayed by default when opening in the crosstab view
