### ISSUE TITLE
population box is better empty or navigation type of text in gray color 

### ISSUE THREAD

**Issue by MahoNagasawa** [tercen/manual_gating_shiny_operator#14]
instead of "pop"in the box, it is better to keep it empty or if possible, navigate a user with "fill here with a population name" kind of text (those disappear when you type something in)

![image](https://user-images.githubusercontent.com/87133370/195108077-46d44986-ae06-4879-a093-cfef804d4aca.png)

**Comment by tsmonteiro** [comment]
Implemented in version 0.5.2
