### ISSUE TITLE
Optimisation: limit the number of API calls

### ISSUE THREAD

**Issue by agouy** [tercen/manual_gating_shiny_operator#3]
Performance can be improved by removing duplicate data queries thorugh the API: select(), rselect(), cselect().

Example: ctx$rselect() occurs 4 times in getData(). It is typically called 3 times during a run (twice in if statement, once afterwards), which means that row data. Assingning the output of rselect to a data frame and using this table afterwards would prevent multiple downloads of the data. Same logic should be applied to select and cselect.

@tsmonteiro @lucaslelann FYI

**Comment by tsmonteiro** [comment]
Removed the excessive calls in version 0.4.4

**Comment by agouy** [comment]
@lucaslelann FYI
